version: '3.8'
services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_data/www/:/var/www/certbot/:rw

  nginx:
    container_name: 'nginx'
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - nuxt
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certbot_data/www:/var/www/certbot/:ro
      - certbot_data/conf/:/etc/nginx/ssl/:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nuxt_data:/app

  nuxt:
    container_name: 'nuxt'
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    networks:
      - nuxt
    ports:
      - '3000:3000'
    volumes:
      - nuxt_data:/app

volumes:
  nuxt_data:
    name: data
    driver: local
  certbot_data:
    name: certbot_data
    driver: local

networks:
  nuxt:
    name: 'nuxt'
    driver: bridge